### ISSUE TITLE
Buyout only option was changed a while ago

### ISSUE THREAD

**Issue by Xebtria** [segfault0/PoETradeOptions#4]
it no longer is an option with "buyout only on/off", but it is a drop down menu "Buyout: Either/Yes/No"

thus, the extension only works for the online only option (as this hasn't changed)

please fix for the new buyout option, thanks

**Comment by segfault0** [comment]
Fixed in version 1.2.0, just pushed to chrome store.  Should be available soon.

**Comment by Xebtria** [comment]
Thanks for fixing that! Just wanted to let you know that it didn't work when updating the extension (options could not be saved). I needed to uninstall and install it new - but then it works. Thanks!

**Comment by segfault0** [comment]
Ah. that is actually another issue.  Just pushed a fix for that as well, so it shouldn't show up again.
